Added inputs to change map size
Jugacu/thisisnotforagerMapEditor pull request #1
Opened 2019-10-24 15:09 UTC by Conejosicopata

Accept me!

2019-10-24 15:25 UTC, Jugacu commented on src/editor/toolbar/InputManager.ts
> +        return !isNaN(n) && min < n && n < max;
Maybe throw an error if the limit is exceded

2019-10-24 15:28 UTC, Jugacu commented on src/editor/toolbar/InputManager.ts
> +        this.gridCount = <HTMLInputElement>document.getElementById('gridCount');
Consider changing this by document.querySelector<HTMLInputElement>

2019-10-24 15:29 UTC, Jugacu commented on src/editor/toolbar/InputManager.ts
> +                       private readonly editor: Editor) {
Consider make this more readable

2019-10-24 15:29 UTC, Jugacu requested changes
Since you reset the map after a grid change maybe warn the user, although would be better if you make it so the map does not get resetted on every change.

For enchancement consider to re center the editor too!

See also code comments

2019-10-25 10:18 UTC, Conejosicopata commented
ready!

2019-10-25 14:02 UTC, merged